name: Goldstrom
favicon: null
layout_spectrum: 0.7900064114946872
typography_spectrum: 0.8156074283178896
title: Michael Goldstrom
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#212123'
    - '#c7c7c9'
    - '#a4a4a6'
    - '#676769'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
